import Head from 'next/head'
import Link from 'next/link'
import { useSession } from 'next-auth/react'

import Header from './header'

export default function Layout({ children, title = 'googleapi sheet' }) {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header session={session} />

      <main className='o-main'>
        <div className='o-wrapper'>{children}</div>
      </main>

      <footer className='o-wrapper o-footer'>
        <Link href='https://bit.ly/36RsoAA' passHref={true}>
          <a target={'_blank'}>
            <span>Powered by </span> <span className='c-link'>@HarleySG</span>
          </a>
        </Link>
      </footer>
    </>
  )
}
