import Head from 'next/head'
import Header from './header'

import { useSession } from "next-auth/react"

export default function Layout({ children, title = 'googleapi sheet' }) {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header session={session} />

      <main className='o-main'>
        <div className='o-wrapper'>{children}</div>
      </main>
    </>
  );
}
