import Head from 'next/head';
import Header from './header';

export default function Layout({ children, title = 'googleapi sheet' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='o-main'>
        <div className='o-wrapper'>{children}</div>
      </main>
    </>
  );
}
