export const DATABASE_SHEETS = {
  CLIENTS: 'CLIENTS',
  ADVISERS: 'ADVISERS'
}

export const SHEET_API_ACTIONS = {
  GET_ALL_CLIENTS: 'GET_ALL_CLIENTS',
  GET_ADVISER_CLIENTS: 'GET_ADVISER_CLIENTS',
  GET_CLIENTS_BY_ID: 'GET_CLIENTS_BY_ID',
}